# Assignment 3: Accessing Array Data


Slice and index the `random_array` we created in the previous exercise. Perform the following:

* Grab the first two 'rows' of the array
* Grab the entire first column
* Finally, grab the second selement of the third row.

Thanks!


In [2]:
import numpy as np
from numpy import random as default_rng

In [9]:
array=default_rng.random(10).reshape(5,2)
array

array([[0.9749804 , 0.91769674],
       [0.67926334, 0.05015013],
       [0.03345537, 0.1753307 ],
       [0.53774154, 0.63566684],
       [0.7828022 , 0.45076841]])

In [14]:
array[:2,:2]

array([[0.9749804 , 0.91769674],
       [0.67926334, 0.05015013]])

In [24]:
array[:,:1]

array([[0.9749804 ],
       [0.67926334],
       [0.03345537],
       [0.53774154],
       [0.7828022 ]])

In [19]:
array[2,1]

np.float64(0.17533070376281457)