# Assignment 4: Arithmetic Operations

The creativity of our marketing team knows no bounds!

They've asked us to come up with a simple algorithm to provide a random discount to our list of prices below. 

Before we do that, 

* Add a 5 dollar shipping fee to each price. Call this array `total`.

Once we have that, we want to use the random_array created in assignment 2 and apply them to the 6 prices.

* Grab the first 6 numbers from `random_array`, reshape it to one dimension. Call this `discount_pct`.
* Subtract `discount_pct` FROM 1, store this in `pct_owed`.
* Multiply `pct_owed` by `total` to get the final amount owed.

In [13]:
import numpy as np
from numpy import random as rng

In [14]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])
total=prices+5
total

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])

In [27]:
random_array=rng.random(9)
random_array

array([0.89257707, 0.6901224 , 0.14097194, 0.86004665, 0.29712962,
       0.35520585, 0.53514735, 0.91583101, 0.31149625])

In [28]:
discount_pct=random_array[:6].reshape(6)
pct_owed=discount_pct-1
final_owed=pct_owed*total


array([ -1.18,  -3.72, -23.61, -14.69,  -7.02, -35.46])

In [31]:
print(discount_pct)
print(pct_owed)
print(final_owed.round(2))

[0.89257707 0.6901224  0.14097194 0.86004665 0.29712962 0.35520585]
[-0.10742293 -0.3098776  -0.85902806 -0.13995335 -0.70287038 -0.64479415]
[ -1.18  -3.72 -23.61 -14.69  -7.02 -35.46]
